export const REQUEST_FLIGHTS = "REQUEST_FLIGHTS";
export const RECEIVED_FLIGHTS = "RECEIVED_FLIGHTS";
export const FLIGHTS_FAILURE = "FLIGHTS_FAILURE";
export const ADD_FLIGHT = "ADD_FLIGHT";
export const REMOVE_FLIGHT = "REMOVE_FLIGHT";
export const SET_FLIGHT_TOTAL_TIME = "SET_FLIGHT_TOTAL_TIME";
